### ISSUE TITLE
Support new Google Analytics 4 (tags that start with G-)

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/googleanalytics#23] opened 2021-01-15 02:19 UTC
This is an issue to track the progress in the Drupal issue of the same title.

The backdrop version of this module contains the patch from 
https://www.drupal.org/project/google_analytics/issues/3178258#comment-13964328

**Comment by jenlampton** [comment] 2021-01-15 02:24
I've committed a change that will allow the new tag to be entered into the UI. I'd like to test this in production on a few sites before I create a release containing it.

**Comment by stpaultim** [comment] 2021-12-15 07:18
@jenlampton - Did you ever release the version with Google Analytics 4?

**Comment by stpaultim** [comment] 2021-12-21 06:06
I installed the dev version and the new "G-" tag does not seem to be working for me.

**Comment by stpaultim** [comment] 2021-12-21 06:22
Sorry, I should have provided more information. 

I installed the dev version of the module. At first, I thought I was seeing the G- tag in the header, but it's days later and no traffic is registering on Google Analytics. I checked the header and there is no G- tag anywhere. 

Afterwards, I realize that I had set ROLE = Anonymous and Authenticated. I was checking for tag in browser I was using as Anonymous, so it should have worked. BUT, when do not select any role - then I do get the tag. 

I'll wait another day now and see if I register any traffic.

**Comment by stpaultim** [comment] 2022-01-05 08:49
Still no luck.

**Comment by stpaultim** [comment] 2022-01-05 23:29
OK, it seems like @jenlampton never tested this, so the problem may be with the module. I've not found anyone else using it with Google Analytics 4 yet. 

I just tried pasting my code directly into the page.tpl.php file and that works fine, which for me confirms that the problem is with the module. It must not be formatting the script correctly.

**Comment by jenlampton** [comment] 2022-01-05 23:51
@stpaultim  it looks like the drupal patch this change was based off does not work either: https://www.drupal.org/project/google_analytics/issues/3178258#comment-13964328 So we should revert and try a different approach.

**Comment by stpaultim** [comment] 2022-01-06 00:00
This seems to be the patch that eventually got committed:
https://www.drupal.org/project/google_analytics/issues/3174214#comment-14234348

It seems like a pretty hefty amount of changes, which frightens me from necessarily trying it myself. I might give it a go anyway.

**Comment by stpaultim** [comment] 2022-05-13 19:27
It's recently been announced that Google is ending support for older versions of Google Analytics. I think it's time we make sure that it's easy to use G4 with Backdrop. 

I'll try again to find some time to work on this Pull Request, but welcome assistance from anyone else.

**Comment by jenlampton** [comment] 2022-06-02 18:53
The [drupal patch](https://www.drupal.org/project/google_analytics/issues/3174214) has been marked RTBC, so I'm going to apply that here and get a new release out.

**Comment by stpaultim** [comment] 2022-06-02 19:19
Thanks. This has come up for me a couple of times in the last few weeks. I was going to raise this again today.

**Comment by jenlampton** [comment] 2022-06-02 19:21
same :)

**Comment by kreynen** [comment] 2022-06-02 20:20
We're loading GA Universal and GA4 through GTM so these module changes aren't going effect me, but I would suggest looking at https://support.google.com/analytics/answer/9744165?hl=en. A few users in the Drupal thread indicated that they were running "side-by-side comparisons".  This is really how the transition from GA Universal and GA4 should happen. GA Universal and GA4 work differently in so many ways, groups that have configured conversions, audience segmentation, search, etc are going to have to rebuild those in GA4 before July 2023.  

Getting support for both GA Universal and GA4 into a stable release now allows you to give everyone a 12 month warning... and many groups are going to need it.

**Comment by stpaultim** [comment] 2022-06-02 23:07
Yes, one of my concerns has been that most of my clients are trying to keep both GA and GA4 running, because they prefer GA right now but want to prepare for GA4. 

I don't think this patch to the module supports both at once. But, I'm willing use work-a-rounds for this.

**Comment by jenlampton** [comment] 2022-06-04 00:06
This patch does support running both GA Universal and GA4 at the same time. I'll test that on my own site and see what happens 🤞

**Closed as completed** 2022-06-23 20:52 UTC
